name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  permissions: write-all
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto test
        run: |
          git config --local user.email "lzh062106@vip.qq.com"
          git config --local user.name "lovexiaobing"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "test"
          git push
