name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto test
        run : |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com
          git pull --rebase
          git commit --allow-empty -m "sjdjxn"
          git push
